# Generated by Django 3.0.3 on 2020-02-29 15:09

from django.db import migrations


def add_meal_types(apps, schema_editor):
    MealType = apps.get_model('camp', 'MealType')
    db_alias = schema_editor.connection.alias
    MealType.objects.using(db_alias).create(name="Lunch")
    MealType.objects.using(db_alias).create(name="Dinner")


def remove_meal_types(apps, schema_editor):
    MealType = apps.get_model('camp', 'MealType')
    db_alias = schema_editor.connection.alias
    MealType.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_meal_types, remove_meal_types)
    ]
