# Generated by Django 3.0.3 on 2020-03-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0002_initial_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='tent',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tent',
            name='name',
            field=models.CharField(default='Tent', max_length=100),
            preserve_default=False,
        ),
    ]
