# Generated by Django 3.0.3 on 2020-03-14 16:45

from django.db import migrations, models
import django.db.models.deletion
import django_utils.choices


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0012_auto_20200314_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('cash', django_utils.choices.Choice('cash', 'Cash')), ('credit', django_utils.choices.Choice('credit', 'Credit'))], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('expenses', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.FoodReservation')),
                ('stay_reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.StayReservation')),
            ],
        ),
    ]
