# Generated by Django 3.0.3 on 2020-04-11 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='food_reservation',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stay_reservation',
        ),
    ]
