# Generated by Django 3.0.3 on 2020-03-01 07:38

from django.db import migrations


def add_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    db_alias = schema_editor.connection.alias
    Group.objects.using(db_alias).create(name='business_owner')
    Group.objects.using(db_alias).create(name='employee')


def delete_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    db_alias = schema_editor.connection.alias
    Group.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0002_user_phone_number'),
    ]

    operations = [
        migrations.RunPython(add_groups, delete_groups)
    ]
