# Generated by Django 3.0.3 on 2020-03-01 07:47
from django.db import migrations

from utils.helpers import create_permissions_in_migrations

business_owner_perms = [
    'add_user', 'change_user', 'delete_user', 'view_user', 'add_activity',
    'change_activity', 'delete_activity', 'view_activity', 'add_food', 'change_food',
    'delete_food', 'view_food', 'add_mealtype', 'change_mealtype', 'delete_mealtype',
    'view_mealtype', 'add_tenttype', 'change_tenttype', 'delete_tenttype', 'view_tenttype',
    'add_tent', 'change_tent', 'delete_tent', 'view_tent', 'add_reservationtype',
    'change_reservationtype', 'delete_reservationtype', 'view_reservationtype', 'add_reservor',
    'change_reservor', 'delete_reservor', 'view_reservor', 'add_staytype', 'change_staytype',
    'view_staytype', 'add_stayreservation', 'change_stayreservation',
    'delete_stayreservation', 'view_stayreservation', 'add_foodreservation',
    'change_foodreservation', 'delete_foodreservation', 'view_foodreservation'
]

employee_perms = [
    'change_activity', 'view_activity', 'view_food', 'view_mealtype',
    'view_tenttype', 'view_tent', 'view_reservationtype',
    'add_reservor', 'change_reservor', 'view_reservor', 'view_staytype',
    'add_stayreservation', 'change_stayreservation', 'view_stayreservation',
    'add_foodreservation', 'change_foodreservation', 'view_foodreservation'
]


def add_groups_perms(apps, schema_editor):
    create_permissions_in_migrations()
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    db_alias = schema_editor.connection.alias
    bo_group = Group.objects.using(db_alias).filter(name='business_owner').first()
    emp_group = Group.objects.using(db_alias).filter(name='employee').first()
    bo_permissions = list(Permission.objects.filter(codename__in=business_owner_perms))
    emp_permissions = list(Permission.objects.filter(codename__in=employee_perms))
    for perm in bo_permissions:
        bo_group.permissions.add(perm)
    bo_group.save()
    for perm in emp_permissions:
        emp_group.permissions.add(perm)
    bo_group.save()


def remove_groups_perms(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    db_alias = schema_editor.connection.alias
    for group in Group.objects.using(db_alias).all():
        group.permissions.clear()


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('authentication', '0003_add_groups'),
        ('camp', '0002_initial_types'),
        ('bookings', '0003_auto_20200229_1529')
    ]

    operations = [
        migrations.RunPython(add_groups_perms, remove_groups_perms)
    ]
