# Generated by Django 3.0.3 on 2020-03-07 11:41
from django.db import migrations

from utils.helpers import create_permissions_in_migrations

bo_perms = ['view_company', 'add_company', 'change_company', 'delete_company']
emp_perms = ['view_company', 'add_company', 'change_company']


def add_company_perms(apps, schema_editor):
    create_permissions_in_migrations()
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    db_alias = schema_editor.connection.alias
    bo_group = Group.objects.using(db_alias).filter(name='business_owner').first()
    emp_group = Group.objects.using(db_alias).filter(name='employee').first()
    bo_permissions = list(Permission.objects.filter(codename__in=bo_perms))
    emp_permissions = list(Permission.objects.filter(codename__in=emp_perms))
    for perm in bo_permissions:
        bo_group.permissions.add(perm)
    for perm in emp_permissions:
        emp_group.permissions.add(perm)


def remove_company_perms(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    db_alias = schema_editor.connection.alias
    bo_group = Group.objects.using(db_alias).filter(name='business_owner').first()
    emp_group = Group.objects.using(db_alias).filter(name='employee').first()
    bo_permissions = list(Permission.objects.filter(codename__in=bo_perms))
    emp_permissions = list(Permission.objects.filter(codename__in=emp_perms))
    for perm in bo_permissions:
        bo_group.permissions.remove(perm)
    for perm in emp_permissions:
        emp_group.permissions.remove(perm)


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0004_add_groups_permissions'),
        ('bookings', '0008_auto_20200307_1140'),
    ]

    run_before = [
        ('bookings', '0009_auto_20200307_1300')
    ]

    operations = [
        migrations.RunPython(add_company_perms, remove_company_perms)
    ]
