# Generated by Django 3.0.3 on 2020-03-14 16:38

from django.db import migrations

from utils.helpers import create_permissions_in_migrations

bo_perms = ['add_payment', 'change_payment', 'delete_payment', 'view_payment']
emp_perms = ['add_payment', 'view_payment']


def add_payment_perms(apps, schema_editor):
    create_permissions_in_migrations()
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    db_alias = schema_editor.connection.alias
    bo_group = Group.objects.using(db_alias).filter(name='business_owner').first()
    emp_group = Group.objects.using(db_alias).filter(name='employee').first()
    bo_permissions = list(Permission.objects.filter(codename__in=bo_perms))
    emp_permissions = list(Permission.objects.filter(codename__in=emp_perms))
    for perm in bo_permissions:
        bo_group.permissions.add(perm)
    for perm in emp_permissions:
        emp_group.permissions.add(perm)


def remove_payment_perms(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    db_alias = schema_editor.connection.alias
    bo_group = Group.objects.using(db_alias).filter(name='business_owner').first()
    emp_group = Group.objects.using(db_alias).filter(name='employee').first()
    bo_permissions = list(Permission.objects.filter(codename__in=bo_perms))
    emp_permissions = list(Permission.objects.filter(codename__in=emp_perms))
    for perm in bo_permissions:
        bo_group.permissions.remove(perm)
    for perm in emp_permissions:
        emp_group.permissions.remove(perm)


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_add_company_permissons'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_payment_perms, remove_payment_perms)
    ]
