# Generated by Django 3.0.3 on 2020-02-29 15:17

from django.db import migrations


def add_stay_types(apps, schema_editor):
    StayType = apps.get_model('bookings', 'StayType')
    db_alias = schema_editor.connection.alias
    StayType.objects.using(db_alias).create(name="Bed & Breakfast")
    StayType.objects.using(db_alias).create(name="Half Board")
    StayType.objects.using(db_alias).create(name="Full Board")


def remove_stay_types(apps, schema_editor):
    StayType = apps.get_model('bookings', 'StayType')
    db_alias = schema_editor.connection.alias
    StayType.objects.using(db_alias).all().delete()


def add_reservation_types(apps, schema_editor):
    ReservationType = apps.get_model('bookings', 'ReservationType')
    db_alias = schema_editor.connection.alias
    ReservationType.objects.using(db_alias).create(name="Company")
    ReservationType.objects.using(db_alias).create(name="Individual")


def remove_reservation_types(apps, schema_editor):
    ReservationType = apps.get_model('bookings', 'ReservationType')
    db_alias = schema_editor.connection.alias
    ReservationType.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_stay_types, remove_stay_types),
        migrations.RunPython(add_reservation_types, remove_reservation_types)
    ]
