# Generated by Django 3.0.3 on 2020-02-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
