# Generated by Django 3.0.3 on 2020-03-01 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0002_initial_types'),
        ('bookings', '0003_auto_20200229_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stayreservation',
            name='tent_type',
        ),
        migrations.AddField(
            model_name='stayreservation',
            name='tent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='camp.Tent'),
        ),
        migrations.AlterField(
            model_name='foodreservation',
            name='reserved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.Reservor'),
        ),
        migrations.AlterField(
            model_name='stayreservation',
            name='reserved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.Reservor'),
        ),
    ]
