# Generated by Django 3.0.3 on 2020-03-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20200301_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodreservation',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stayreservation',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
