# Generated by Django 3.0.3 on 2020-03-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_foodreservation_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodreservation',
            name='reservation_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stayreservation',
            name='reservation_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
