# Generated by Django 3.0.3 on 2020-03-07 11:40

from django.db import migrations, models
import django.db.models.deletion
import django_utils.choices


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_auto_20200303_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='foodreservation',
            name='reserved_by',
        ),
        migrations.RemoveField(
            model_name='stayreservation',
            name='reserved_by',
        ),
        migrations.AddField(
            model_name='foodreservation',
            name='contact_email',
            field=models.EmailField(default='radwan@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodreservation',
            name='contact_name',
            field=models.CharField(default='radwan', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodreservation',
            name='contact_number',
            field=models.CharField(default='0791512538', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stayreservation',
            name='contact_email',
            field=models.EmailField(default='radwan@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stayreservation',
            name='contact_name',
            field=models.CharField(default='radwan', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stayreservation',
            name='contact_number',
            field=models.CharField(default='0791512538', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodreservation',
            name='reservation_type',
            field=models.CharField(choices=[('individual', django_utils.choices.Choice('individual', 'Individual')), ('company', django_utils.choices.Choice('company', 'Company'))], default='individual', max_length=50),
        ),
        migrations.AlterField(
            model_name='stayreservation',
            name='reservation_type',
            field=models.CharField(choices=[('individual', django_utils.choices.Choice('individual', 'Individual')), ('company', django_utils.choices.Choice('company', 'Company'))], default='individual', max_length=50),
        ),
        migrations.DeleteModel(
            name='ReservationType',
        ),
        migrations.DeleteModel(
            name='Reservor',
        ),
        migrations.AddField(
            model_name='foodreservation',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.Company'),
        ),
        migrations.AddField(
            model_name='stayreservation',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.Company'),
        ),
    ]
