# Generated by Django 3.0.3 on 2020-03-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_auto_20200307_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
