# Generated by Django 3.0.3 on 2020-03-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_auto_20200307_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodreservation',
            name='contact_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='foodreservation',
            name='contact_number',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='foodreservation',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='stayreservation',
            name='contact_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='stayreservation',
            name='contact_number',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='stayreservation',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
