# Generated by Django 3.0.3 on 2020-03-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_auto_20200314_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodreservation',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='foodreservation',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stayreservation',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stayreservation',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
